project:
  title: "Quarto "
  type: website
  output-dir: ../docs

format:
  html:
    code-fold: true
    html-math-method: katex
    theme: [default, img/evelyn_2023.scss]
    css: img/evelyn_2023.css
    toc: true

  

website:
  title: "No/Low Code Workshop"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: https://ejboettcher.github.io/gemcityML-No-CodeAI/application_demo/index.html
        text: "Web App Demo"
      - href: slide_deck.html
        text: Slides
      - href: lessonplan.qmd
        text: "Lesson Plan"
      - href: https://github.com/ejboettcher/gemcityML-No-CodeAI/tree/main/docs/student_application_starter
        text: "Student App Code"

execute:
  echo: true
  output: true
  error: true

jupyter: python3




